[package]
name = "server"
version = "0.1.0"
edition = "2021"  # or "2018"

[[bin]]
name = "server"
path = "main.rs"

[dependencies]
hyper = { version = "0.14", features = ["full", "server"] }
tokio = { version = "1", features = ["full"] }
